insert into blog.categories (id, name, slug, created_at, updated_at) values (1, 'Work', 'work', '2022-01-30 17:34:14', '2022-01-30 17:34:14');
insert into blog.categories (id, name, slug, created_at, updated_at) values (2, 'Personal', 'personal', '2022-01-30 17:34:28', '2022-01-30 17:34:28');
insert into blog.categories (id, name, slug, created_at, updated_at) values (3, 'Hobbies', 'hobbies', '2022-01-30 17:34:42', '2022-01-30 17:34:42');

insert into blog.posts (slug, category_id, title, excerpt, body, published_at, created_at, updated_at)
values ('my-personal-post', '2', 'My Personal Post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', null, '2022-01-29 18:07:06', '2022-01-29 18:07:06');
insert into blog.posts (slug, category_id, title, excerpt, body, published_at, created_at, updated_at)
values ('my-work_post', '1', 'My Work Post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', null, '2022-01-29 18:07:51', '2022-01-29 18:07:51');
insert into blog.posts (slug, category_id, title, excerpt, body, published_at, created_at, updated_at)
values ('my-hobbies-post', '3', 'My Hobbies Post', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', null, '2022-01-29 18:16:41', '2022-01-29 18:16:41');
